### ISSUE TITLE
Add WILLEM_TUNED version for cpp_powersort_4way?

### ISSUE THREAD

**Issue by ilazaric** [Voultapher/sort-research-rs#15]
Something along the lines of:

```
template<typename T>
void powersort_4way_willem_generic(T* data, size_t len){
  T* mid1 = std::partition(data, data+len, [](const T& el){return el < T{};});
  T* mid2 = std::partition(mid1, data+len, [](const T& el){return el == T{};});
  // sort [data, mid1> range
  // sort [mid2, data+len> range
}
```

That doesn't require the sentinel to not appear in the sequence

For the performance benchmarks it might be interesting

It might make sense to make it generic over the sentinel, to test both `T{}` and `std::numeric_limits<uint64_t>::max()` ? Not familiar with the algo :\

**Comment by Voultapher** [comment]
If all you want to do is, try out the perf of `WILLEM_TUNED` you can change this line https://github.com/Voultapher/sort-research-rs/blob/b131ed6189ef28a6aa72a26670a769b1a5e4ed33/src/cpp/cpp_powersort.cpp#L28. I don't enable it by default, because I consider doing so an unfair comparison. I'm only interested in functional sort implementations, and in my eyes enabling this feature renders it non-functional.

Please let me know if that addresses your concern.

**Comment by Voultapher** [comment]
I'm closing this now, feel free to re-open if you think the issue was not addressed.
