### ISSUE TITLE
Merging method used with driftsort and its memory usage

### ISSUE THREAD

**Issue by TS60** [Voultapher/sort-research-rs#28]
Hi, it seems that you have decided to use the normal tape merge algorithm, which is known to have many advantages, with driftsort.
> Merge: Branchless merge derived from the current slice::sort implementation. Requires at most N / 2 auxiliary memory.

Unfortunately it requires N/2 extra memory. Thus, I'm interested if you have tried one of the O(sqrt(N)) memory usage merging methods like shown [here](https://github.com/TS60/novel-algorithms?tab=readme-ov-file#merging-with-osqrtn-memory-and-the-optimal-number-of-comparisons) or [here](https://github.com/TS60/novel-algorithms?tab=readme-ov-file#the-same-idea-applied-to-an-other-algorithm)? Both of them use the same number of comparisons like the normal method. I have not implemented them myself, it is possible that they slow down too much. Maybe you have tested one of these during the research. If so, I would be very interested about the runtime differences. Thanks!

**Comment by Voultapher** [comment]
Hi, sorry for the late reply.

> Thus, I'm interested if you have tried one of the O(sqrt(N)) memory usage merging methods like shown here or here?

Not exactly the ones you outline, but glidesort from which some parts of driftsort were adapted, uses merge splitting which allows it to use a fixed size buffer of e.g. 1024 elements to amortize the auxiliary memory usage to a constant.

We decided to not port over this part for a couple of reasons:

* Compile-time and binary-size scale nearly directly with implementation complexity and LoCs. So we tried to cut down every part to the bare minimum that still achieved a good mix of the design goals. This is a global optimization function, we decided to spend more of the LoC budget on the quicksort than the merge, which is only relevant for very large inputs, pre-sorted inputs and as a fallback. The quicksort in contrast covers the vast majority of inputs seen in the real world.
* Users are already used to N/2 memory usage, so if we can get faster run-time we use the memory available. We even go the other direction using N memory up to ~8MB to improve run-time. Other generic implementations such as fluxsort or the C++ stdlib implementations always use N memory.
* Merging involves working with temporary copies of the data, which makes reasoning about the code a substantial challenge because it needs to uphold [Ord safety](https://github.com/Voultapher/sort-research-rs/blob/main/writeup/sort_safety/text.md#ord-safety) [Panic safety](https://github.com/Voultapher/sort-research-rs/blob/main/writeup/sort_safety/text.md#ord-safety) and [Observation safety](https://github.com/Voultapher/sort-research-rs/blob/main/writeup/sort_safety/text.md#observation-safety). Merging sits right at the intersection of all three, with many duplicate elements in flight. So by using a known good method -- with slight tweaks -- we reduced the risk of not achieving our safety goal.

If I understand your algorithms correctly they would invariably be both more complex and potentially slower. So the reasons outlined above probably make them a poor fit for `slice::sort` as well.

**Comment by TS60** [comment]
Thanks for the answer! Yes, I also think they are more complex to implement. They can have sqrt(N) extra cache misses, and maybe one extra branch per comparisons, I think. Otherwise, it is the same algorithm like the default method. But I definetly understand the advantages of the tape merge method.
